### ISSUE TITLE
Informal description of the rot files

### ISSUE THREAD

**Issue by favonia** [RedPRL/redtt#392]
The *rot* format is to store elaborated (and 99% normalized) redtt definitions to speed up imports. A *rot* file is a YAML file consisting of four sections:

0. file format version
1. dependencies
2. resource imports
3. resource

This is assuming `redlib` cannot change the semantics of `red` or `rot` files in any way.

---

The file format version section is
```yaml
version: 0
```
which denotes the format version of this *rot* file.

---

The dependency section is
```yaml
deps:
- method: redsum
  params:
  - 372cd79a70ea07d2b4d82a4ee320a2c5
- method: rotsum
  params:
  - fun
  - d860de4a96da39d24047d8fe68eb2d39
- method: rotsum
  params:
  - nat
  - 8002bb15defde74ee7e5fd4c5539ec0f
```
where each item describes a precondition. Only when all the preconditions hold a *rot* file is considered usable. `method` refers to a hook supported by the dependency checker and `params` are the parameters fed into the hook. Currently, in version 0, the following hooks are supported:

- `false`: always false.
- `true`: always true.
- `redsum [hash]`: true if the checksum of the corresponding `red` file is `hash`.
- `rotsum [selector, hash]`: true if the checksum of the corresponding `red` file is `hash`.
- `shell [cmd, output]`: run the command `cmd` through `system` and compare its output with `output`.

---

The resource imports section is
```yaml
imports:
- type: rot
  params: ["fun"]
  children:
  - type: rot
    params: ["base"]
    children: []
- type: rot
  params: ["nat"]
  children: []
```
which gives a list of other resources that can be accessed from the resource section. It is assumed that there is no self-importing or other cyclic references. The resource section should be self-contained except for possible references to some resource listed in this section. Currently, the only supported type is `rot`, which is to generate a `rot` file from a `red` file (if non-existing or unusable) and import its content.

---

Finally, the resource section is
```yaml
data:
- type: def
  params:
  - id
  - "(pi (U kan) [0] (pi 0 [1] 0))"
  - "(lookup (0 1) id)"
- type: data
  params:
  - s1
  - ...
- type: opaque def
  params:
  - magic
  - "(path [0] (lookup (1) nat) (lookup (1) zero) ((lookup (1) suc) (lookup (1) zero))"
```
which intends to store the fully elaborated redtt signatures. The exact format is work in progress. Note that the resource section *must be self-contained* except for possible references to the resources listed in the "imports" section. The reference format is `(lookup (num+) string*)` which would look up the resource.

---

Necessary changes to the current framework.

0. The elaborator should not control the import procedure. Instead, the elaborator should be a routine under the control of another module orchestrating the entire compilation process.
